name: Build and release Zenon CLI for .NET

on:
  push:
    branches: main

  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    env:
      PROJECT_PATH: src/ZenonCli/ZenonCli.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Setup Nerdbank Git versioning
        run: nbgv install

      - name: Restore dependencies
        run: dotnet restore $env:PROJECT_PATH

      - name: Build
        run: dotnet build $env:PROJECT_PATH --no-restore 

      - name: Test
        run: dotnet test $env:PROJECT_PATH --no-build --verbosity normal

      - name: Package into zip
        run: |
          Compress-Archive -Path bin\ZenonCli\net6.0\* -DestinationPath .\znn-cli-dotnet-windows-amd64.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-artifacts
          path: znn-cli-dotnet-windows-amd64.zip

  build-linux:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          
      - name: Setup Nerdbank Git versioning
        run: nbgv install

      - name: Restore dependencies
        run: dotnet restore src/ZenonCli/ZenonCli.csproj

      - name: Build
        run: dotnet build src/ZenonCli/ZenonCli.csproj --no-restore --runtime linux-x64

      - name: Test
        run: dotnet test src/ZenonCli/ZenonCli.csproj --no-build --verbosity normal

      - name: Package zip
        run: |
          cd bin/ZenonCli/net6.0/linux-x64
          zip -r ../../../../znn-cli-dotnet-linux-amd64.zip *

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifacts
          path: znn-cli-dotnet-linux-amd64.zip
